
    measurements<-read.csv(file=file.path(logfile[[1]],"dataframes","measurements"),colClasses = "character");
	measurements<-measurements[measurements[,8]=="TRUE",,drop=FALSE]
	if(any(measurements[,4]=="positive")){
		if(any(objects(envir=as.environment(".GlobalEnv"))=="peaklist")){rm(peaklist,envir=as.environment(".GlobalEnv"))}
		if(any(objects()=="peaklist")){rm(peaklist)}
		if(any(objects(envir=as.environment(".GlobalEnv"))=="profileList_pos")){rm(profileList_pos,envir=as.environment(".GlobalEnv"))}
		if(any(objects()=="profileList_pos")){rm(profileList_pos)}		
		if(file.exists(file.path(as.character(logfile[[1]]),"results","profileList_pos"))){file.remove(file.path(as.character(logfile[[1]]),"results","profileList_pos"))}
		if(file.exists(file.path(as.character(logfile[[1]]),"results","profileList_pos_copy"))){file.remove(file.path(as.character(logfile[[1]]),"results","profileList_pos_copy"))}
		profileList_pos<-startprofiles(
							logfile,
							frac=FALSE,
							sets=as.numeric(logfile$parameters$prof_maxfiles),
							progbar=logfile$parameters$progressBar,
							ion_mode="positive",
							until=logfile$parameters$upto_file,
							selective=logfile$parameters$prof_select,
							types=c("sample","blank")
						)
		profileList_pos<-agglomer(
							profileList_pos,
							dmass=(as.numeric(logfile$parameters$prof_dmz)+1),
							ppm=as.logical(as.character(logfile$parameters$prof_ppm)),
							dret=(as.numeric(logfile$parameters$prof_drt)+10)
						)
		if(logfile$parameters[[91]]=="no"){ 				
			profileList_pos<-partcluster(
								profileList=profileList_pos,
								dmass=as.numeric(logfile$parameters$prof_dmz),
								ppm=as.logical(as.character(logfile$parameters$prof_ppm)),
								dret=as.numeric(logfile$parameters$prof_drt),
								from=FALSE,
								to=FALSE,
								progbar=logfile$parameters$progressBar,
								plotit=FALSE,
								replicates=FALSE
							)
		}else{ # run a profiling in the replicate groups first
			measurements<-read.csv(file=file.path(logfile[[1]],"dataframes","measurements"),colClasses = "character");
			measurements<-measurements[measurements[,8]=="TRUE",]
			measurements<-measurements[measurements[,4]=="positive",]
			replicates<-measurements$tag3
			IDs<-measurements$ID
			profileList_pos<-partcluster(
								profileList=profileList_pos,
								dmass=as.numeric(logfile$parameters$prof_dmz),
								ppm=as.logical(as.character(logfile$parameters$prof_ppm)),
								dret=as.numeric(logfile$parameters$prof_drt),
								from=FALSE,
								to=FALSE,
								progbar=logfile$parameters$progressBar,
								plotit=FALSE,
								replicates=replicates,
								IDs
							)
		}
		profileList_pos<-enviMass:::in_blind(profileList_pos)
		profileList_pos<<-profileList_pos
		save(profileList_pos,file=file.path(as.character(logfile[[1]]),"results","profileList_pos"));
		profileList_pos_copy<-profileList_pos
		save(profileList_pos_copy,file=file.path(as.character(logfile[[1]]),"results","profileList_pos_copy")); # used for screening - does not include modifications of downstream compound subtraction		
		profpeaks_pos<-enviMass:::profiletopeak(profileList_pos,progbar=logfile$parameters[21])		
		profpeaks_pos<-profpeaks_pos[order(profpeaks_pos[,13],decreasing=TRUE),];
		profpeaks_pos<<-profpeaks_pos;
		save(profpeaks_pos,file=file.path(as.character(logfile[[1]]),"results","profpeaks_pos"));
		links_peaks_pos<-list(); # each entry with 3 lists itself: targets, IS, other components
		save(links_peaks_pos,file=file.path(as.character(logfile[[1]]),"results","links_peaks_pos"));	
		links_profiles_pos<-list();
		save(links_profiles_pos,file=file.path(as.character(logfile[[1]]),"results","links_profiles_pos"));				
	}
	if(any(measurements[,4]=="negative")){
		if(any(objects(envir=as.environment(".GlobalEnv"))=="peaklist")){rm(peaklist,envir=as.environment(".GlobalEnv"))}
		if(any(objects()=="peaklist")){rm(peaklist)}
		if(any(objects(envir=as.environment(".GlobalEnv"))=="profileList_neg")){rm(profileList_neg,envir=as.environment(".GlobalEnv"))}
		if(any(objects()=="profileList_neg")){rm(profileList_neg)}	
		if(file.exists(file.path(as.character(logfile[[1]]),"results","profileList_neg"))){file.remove(file.path(as.character(logfile[[1]]),"results","profileList_neg"))}
		if(file.exists(file.path(as.character(logfile[[1]]),"results","profileList_neg_copy"))){file.remove(file.path(as.character(logfile[[1]]),"results","profileList_neg_copy"))}
		profileList_neg<-startprofiles(
							logfile,
							frac=FALSE,
							sets=as.numeric(logfile$parameters$prof_maxfiles),
							progbar=logfile$parameters$progressBar,
							ion_mode="negative",
							until=logfile$parameters$upto_file,
							selective=logfile$parameters[[90]],
							types=c("sample","blank")
						)
		profileList_neg<-agglomer(
							profileList_neg,
							dmass=(as.numeric(logfile$parameters$prof_dmz)+1),
							ppm=as.logical(as.character(logfile$parameters$prof_ppm)),
							dret=(as.numeric(logfile$parameters$prof_drt)+10)
						)
		if(logfile$parameters[[91]]=="no"){ 				
			profileList_neg<-partcluster(
								profileList_neg,
								dmass=as.numeric(logfile$parameters$prof_dmz),
								ppm=as.logical(as.character(logfile$parameters$prof_ppm)),
								dret=as.numeric(logfile$parameters$prof_drt),
								from=FALSE,
								to=FALSE,
								progbar=logfile$parameters$progressBar,
								plotit=FALSE
							)
		}else{ # run a profiling in the replicate groups first
			measurements<-read.csv(file=file.path(logfile[[1]],"dataframes","measurements"),colClasses = "character");
			measurements<-measurements[measurements[,8]=="TRUE",]
			measurements<-measurements[measurements[,4]=="negative",]
			replicates<-measurements$tag3
			IDs<-measurements$ID
			profileList_neg<-partcluster(
								profileList=profileList_neg,
								dmass=as.numeric(logfile$parameters$prof_dmz),
								ppm=as.logical(as.character(logfile$parameters$prof_ppm)),
								dret=as.numeric(logfile$parameters$prof_drt),
								from=FALSE,
								to=FALSE,
								progbar=logfile$parameters$progressBar,
								plotit=FALSE,
								replicates=replicates,
								IDs
							)
		}
		profileList_neg<-enviMass:::in_blind(profileList_neg)
		profileList_neg<<-profileList_neg
		save(profileList_neg,file=file.path(as.character(logfile[[1]]),"results","profileList_neg"));
		profileList_neg_copy<-profileList_neg
		save(profileList_neg_copy,file=file.path(as.character(logfile[[1]]),"results","profileList_neg_copy")); # used for screening - does not include modifications of downstream compound subtraction			
		profpeaks_neg<-enviMass:::profiletopeak(profileList_neg,progbar=logfile$parameters[21])
		profpeaks_neg<-profpeaks_neg[order(profpeaks_neg[,13],decreasing=TRUE),]
		profpeaks_neg<<-profpeaks_neg;
		save(profpeaks_neg,file=file.path(as.character(logfile[[1]]),"results","profpeaks_neg"));
		links_peaks_neg<-list();
		save(links_peaks_neg,file=file.path(as.character(logfile[[1]]),"results","links_peaks_neg"));
		links_profiles_neg<-list();
		save(links_profiles_neg,file=file.path(as.character(logfile[[1]]),"results","links_profiles_neg"));			
	}

