
		path=file.path(logfile[[1]],"pics","profnorm_pos")
			png(filename = path, bg = "white")
			plot.new();plot.window(xlim=c(0,1),ylim=c(0,1));text(0.5,0.5,"nothing selected \n or not available",cex=1)
			dev.off()
		    expr30p<-list(src=path)
			output$profnorm_pos<-renderImage(expr30p, deleteFile = FALSE)		
		path=file.path(logfile[[1]],"pics","profcount_pos")
			png(filename = path, bg = "white")
			plot.new();plot.window(xlim=c(1,1),ylim=c(1,1));#box();text(1,1,label="not available",cex=1.5,col="darkred")
			dev.off()
		    expr31p<-list(src=path)
			output$profcount_pos<-renderImage(expr31p, deleteFile = FALSE)
		path=file.path(logfile[[1]],"pics","profnorm_neg")
			png(filename = path, bg = "white")
			plot.new();plot.window(xlim=c(0,1),ylim=c(0,1));text(0.5,0.5,"nothing selected \n or not available",cex=1)
			dev.off()
		    expr30n<-list(src=path)
			output$profnorm_neg<-renderImage(expr30n, deleteFile = FALSE)		
		path=file.path(logfile[[1]],"pics","profcount_neg")
			png(filename = path, bg = "white")
			plot.new();plot.window(xlim=c(1,1),ylim=c(1,1));#box();text(1,1,label="not available",cex=1.5,col="darkred")
			dev.off()
		    expr31n<-list(src=path)
			output$profcount_neg<-renderImage(expr31n, deleteFile = FALSE)		

